### PR TITLE
NTT refactor

### PR DESCRIPTION
**Pull request by mcarilli**
# What ❔

This PR implements new NTT kernels with improved data movement.

## Why ❔

The new code is cleaner (gets rid of ugly macros) and modestly faster due to streamlined twiddle handling. New kernels also eliminate bank conflicts without shared memory padding, which allows exact power-of-two smem allocations and improves max occupancy on some architectures.

Benchmarks on gcp L4 with cuda 12.3 are posted below. I ran them separately because when i run the entire suite at once, later benchmarks often appear slower (power or temp throttled?) even if i lock clocks.
TLDR: Speedup is modest (a few %) for non-LDEs, hit-or-miss for LDEs. I think the improved code cleanliness, clear twiddle handling, and power-of-two smem allocations are still worth landing.

For each ntt size, benchmarks run a batch with a number of ntts such that total problem size (num ntts * ntt size) is 1 GB. This is too big to take advantage of L2 residence across kernels. Therefore, for smaller ntt sizes, end to end time per ntt is longer than what you'd see for smaller batches. L2-aware chunking of large batches is a good optimization to consider, but is roughly agnostic to the kernels themselves and can be implemented as a followup.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Include benchmarks
- [x] Code has been formatted via `cargo fmt` and linted via `cargo clippy`.

### CODE REVIEW

**Comment by mcarilli** [comment]
bitrev->nonbitrev, fwd

```
batch_ntt/inverse, n2b, size 2^16
                        time:   [371.78 ms 372.34 ms 374.59 ms]
                        thrpt:  [9.1454 µs/elem 9.0903 µs/elem 9.0765 µs/elem]
batch_ntt/inverse, n2b, size 2^17
                        time:   [380.44 ms 387.30 ms 389.01 ms]
                        thrpt:  [18.995 µs/elem 18.911 µs/elem 18.576 µs/elem]
batch_ntt/inverse, n2b, size 2^18
                        time:   [379.37 ms 390.58 ms 393.38 ms]
                        thrpt:  [38.416 µs/elem 38.143 µs/elem 37.048 µs/elem]
batch_ntt/inverse, n2b, size 2^19
                        time:   [381.28 ms 394.18 ms 397.41 ms]
                        thrpt:  [77.618 µs/elem 76.988 µs/elem 74.468 µs/elem]
batch_ntt/inverse, n2b, size 2^20
                        time:   [387.01 ms 403.99 ms 408.24 ms]
                        thrpt:  [159.47 µs/elem 157.81 µs/elem 151.17 µs/elem]
batch_ntt/inverse, n2b, size 2^21
                        time:   [569.13 ms 569.28 ms 569.88 ms]
                        thrpt:  [445.22 µs/elem 444.75 µs/elem 444.63 µs/elem]
batch_ntt/inverse, n2b, size 2^22
                        time:   [569.65 ms 569.95 ms 571.18 ms]
                        thrpt:  [892.47 µs/elem 890.55 µs/elem 890.08 µs/elem]
batch_ntt/inverse, n2b, size 2^23
                        time:   [570.31 ms 570.43 ms 570.90 ms]
                        thrpt:  [1.7841 ms/elem 1.7826 ms/elem 1.7822 ms/elem]
batch_ntt/inverse, n2b, size 2^24
                        time:   [570.15 ms 572.99 ms 573.70 ms]
                        thrpt:  [3.5856 ms/elem 3.5812 ms/elem 3.5634 ms/elem]
```

**Comment by mcarilli** [comment]
### bitrev -> nonbitrev, fwd

PR
```
batch_ntt/forward, b2n, size 2^16
                        time:   [373.01 ms 373.06 ms 373.27 ms]
                        thrpt:  [9.1131 µs/elem 9.1080 µs/elem 9.1068 µs/elem]
batch_ntt/forward, b2n, size 2^17
                        time:   [374.17 ms 375.15 ms 375.40 ms]
                        thrpt:  [18.330 µs/elem 18.318 µs/elem 18.270 µs/elem]
batch_ntt/forward, b2n, size 2^18
                        time:   [374.09 ms 380.16 ms 381.68 ms]
                        thrpt:  [37.273 µs/elem 37.125 µs/elem 36.532 µs/elem]
batch_ntt/forward, b2n, size 2^19
                        time:   [373.52 ms 381.21 ms 383.14 ms]
                        thrpt:  [74.831 µs/elem 74.456 µs/elem 72.953 µs/elem]
batch_ntt/forward, b2n, size 2^20
                        time:   [375.04 ms 388.74 ms 392.16 ms]
                        thrpt:  [153.19 µs/elem 151.85 µs/elem 146.50 µs/elem]
batch_ntt/forward, b2n, size 2^21
                        time:   [566.93 ms 567.24 ms 568.48 ms]
                        thrpt:  [444.12 µs/elem 443.15 µs/elem 442.91 µs/elem]
batch_ntt/forward, b2n, size 2^22
                        time:   [567.47 ms 568.25 ms 571.37 ms]
                        thrpt:  [892.76 µs/elem 887.89 µs/elem 886.67 µs/elem]
batch_ntt/forward, b2n, size 2^23
                        time:   [565.99 ms 566.28 ms 567.45 ms]
                        thrpt:  [1.7733 ms/elem 1.7696 ms/elem 1.7687 ms/elem]
batch_ntt/forward, b2n, size 2^24
                        time:   [565.91 ms 567.72 ms 568.18 ms]
                        thrpt:  [3.5511 ms/elem 3.5483 ms/elem 3.5369 ms/elem]
```

**Comment by mcarilli** [comment]
### bitrev -> nonbitrev, inv

PR:
```
batch_ntt/inverse, b2n, size 2^16
                        time:   [371.15 ms 371.40 ms 372.40 ms]
                        thrpt:  [9.0917 µs/elem 9.0674 µs/elem 9.0613 µs/elem]
batch_ntt/inverse, b2n, size 2^17
                        time:   [374.30 ms 377.67 ms 378.51 ms]
                        thrpt:  [18.482 µs/elem 18.441 µs/elem 18.276 µs/elem]
batch_ntt/inverse, b2n, size 2^18
                        time:   [374.44 ms 380.60 ms 382.15 ms]
                        thrpt:  [37.319 µs/elem 37.168 µs/elem 36.566 µs/elem]
batch_ntt/inverse, b2n, size 2^19
                        time:   [374.05 ms 382.30 ms 384.36 ms]
                        thrpt:  [75.070 µs/elem 74.667 µs/elem 73.056 µs/elem]
batch_ntt/inverse, b2n, size 2^20
                        time:   [377.75 ms 389.30 ms 392.18 ms]
                        thrpt:  [153.20 µs/elem 152.07 µs/elem 147.56 µs/elem]
batch_ntt/inverse, b2n, size 2^21
                        time:   [565.55 ms 565.65 ms 566.08 ms]
                        thrpt:  [442.25 µs/elem 441.92 µs/elem 441.84 µs/elem]
batch_ntt/inverse, b2n, size 2^22
                        time:   [567.54 ms 568.05 ms 570.09 ms]
                        thrpt:  [890.76 µs/elem 887.58 µs/elem 886.79 µs/elem]
batch_ntt/inverse, b2n, size 2^23
                        time:   [568.09 ms 568.79 ms 568.97 ms]
                        thrpt:  [1.7780 ms/elem 1.7775 ms/elem 1.7753 ms/elem]
batch_ntt/inverse, b2n, size 2^24
                        time:   [568.52 ms 568.53 ms 568.54 ms]
                        thrpt:  [3.5534 ms/elem 3.5533 ms/elem 3.5532 ms/elem]
```

**Comment by mcarilli** [comment]
### nonbitrev -> bitrev, fwd LDE

<details>

```
batch_lde/forward, n2b, size 2^16
                        time:   [374.39 ms 391.72 ms 396.05 ms]
                        thrpt:  [9.6692 µs/elem 9.5634 µs/elem 9.1404 µs/elem]
batch_lde/forward, n2b, size 2^17
                        time:   [410.61 ms 411.21 ms 413.59 ms]
                        thrpt:  [20.195 µs/elem 20.078 µs/elem 20.049 µs/elem]
batch_lde/forward, n2b, size 2^18
                        time:   [421.57 ms 421.99 ms 423.65 ms]
                        thrpt:  [41.372 µs/elem 41.210 µs/elem 41.169 µs/elem]
batch_lde/forward, n2b, size 2^19
                        time:   [431.00 ms 431.64 ms 434.20 ms]
                        thrpt:  [84.805 µs/elem 84.304 µs/elem 84.179 µs/elem]
batch_lde/forward, n2b, size 2^20
                        time:   [442.16 ms 442.56 ms 444.19 ms]
                        thrpt:  [173.51 µs/elem 172.88 µs/elem 172.72 µs/elem]
batch_lde/forward, n2b, size 2^21
                        time:   [566.55 ms 566.66 ms 567.09 ms]
                        thrpt:  [443.04 µs/elem 442.70 µs/elem 442.62 µs/elem]
batch_lde/forward, n2b, size 2^22
                        time:   [568.09 ms 572.28 ms 573.33 ms]
                        thrpt:  [895.82 µs/elem 894.19 µs/elem 887.63 µs/elem]
```
</details>

**Comment by mcarilli** [comment]
### nonbitrev -> bitrev, inv LDE


```
batch_lde/inverse, n2b, size 2^16
                        time:   [416.13 ms 427.64 ms 430.52 ms]
                        thrpt:  [10.511 µs/elem 10.440 µs/elem 10.159 µs/elem]
batch_lde/inverse, n2b, size 2^17
                        time:   [459.37 ms 468.98 ms 471.38 ms]
                        thrpt:  [23.017 µs/elem 22.899 µs/elem 22.430 µs/elem]
batch_lde/inverse, n2b, size 2^18
                        time:   [470.03 ms 481.71 ms 484.63 ms]
                        thrpt:  [47.327 µs/elem 47.042 µs/elem 45.901 µs/elem]
batch_lde/inverse, n2b, size 2^19
                        time:   [476.37 ms 488.68 ms 491.75 ms]
                        thrpt:  [96.046 µs/elem 95.445 µs/elem 93.041 µs/elem]
batch_lde/inverse, n2b, size 2^20
                        time:   [489.56 ms 505.22 ms 509.14 ms]
                        thrpt:  [198.88 µs/elem 197.35 µs/elem 191.23 µs/elem]
batch_lde/inverse, n2b, size 2^21
                        time:   [576.08 ms 588.66 ms 591.80 ms]
                        thrpt:  [462.35 µs/elem 459.89 µs/elem 450.06 µs/elem]
batch_lde/inverse, n2b, size 2^22
                        time:   [624.92 ms 637.49 ms 640.63 ms]
                        thrpt:  [1.0010 ms/elem 996.08 µs/elem 976.44 µs/elem]
```

**Comment by mcarilli** [comment]
### bitrev -> nonbitrev, fwd LDE

<details>
<summary>PR:</summary>

```
batch_lde/forward, b2n, size 2^16
                        time:   [403.22 ms 420.00 ms 424.19 ms]
                        thrpt:  [10.356 µs/elem 10.254 µs/elem 9.8442 µs/elem]
batch_lde/forward, b2n, size 2^17
                        time:   [441.72 ms 459.00 ms 463.32 ms]
                        thrpt:  [22.623 µs/elem 22.412 µs/elem 21.568 µs/elem]
batch_lde/forward, b2n, size 2^18
                        time:   [450.51 ms 467.29 ms 471.48 ms]
                        thrpt:  [46.043 µs/elem 45.634 µs/elem 43.995 µs/elem]
batch_lde/forward, b2n, size 2^19
                        time:   [460.35 ms 476.59 ms 480.65 ms]
                        thrpt:  [93.876 µs/elem 93.084 µs/elem 89.913 µs/elem]
batch_lde/forward, b2n, size 2^20
                        time:   [472.58 ms 490.03 ms 494.40 ms]
                        thrpt:  [193.12 µs/elem 191.42 µs/elem 184.60 µs/elem]
batch_lde/forward, b2n, size 2^21
                        time:   [565.49 ms 576.08 ms 578.73 ms]
                        thrpt:  [452.13 µs/elem 450.06 µs/elem 441.79 µs/elem]
batch_lde/forward, b2n, size 2^22
                        time:   [609.56 ms 626.28 ms 630.46 ms]
                        thrpt:  [985.09 µs/elem 978.56 µs/elem 952.44 µs/elem]
```
</details>

**Comment by mcarilli** [comment]
### bitrev -> nonbitrev, fwd LDE

<details>
<summary>PR:</summary>

```
batch_lde/inverse, b2n, size 2^16
                        time:   [402.56 ms 403.30 ms 406.27 ms]
                        thrpt:  [9.9188 µs/elem 9.8463 µs/elem 9.8282 µs/elem]
batch_lde/inverse, b2n, size 2^17
                        time:   [418.33 ms 418.69 ms 420.14 ms]
                        thrpt:  [20.515 µs/elem 20.444 µs/elem 20.426 µs/elem]
batch_lde/inverse, b2n, size 2^18
                        time:   [428.92 ms 429.37 ms 431.18 ms]
                        thrpt:  [42.107 µs/elem 41.931 µs/elem 41.887 µs/elem]
batch_lde/inverse, b2n, size 2^19
                        time:   [428.72 ms 429.19 ms 431.07 ms]
                        thrpt:  [84.193 µs/elem 83.825 µs/elem 83.734 µs/elem]
batch_lde/inverse, b2n, size 2^20
                        time:   [436.59 ms 437.07 ms 438.98 ms]
                        thrpt:  [171.48 µs/elem 170.73 µs/elem 170.54 µs/elem]
batch_lde/inverse, b2n, size 2^21
                        time:   [570.57 ms 572.13 ms 572.52 ms]
                        thrpt:  [447.28 µs/elem 446.98 µs/elem 445.76 µs/elem]
batch_lde/inverse, b2n, size 2^22
                        time:   [571.72 ms 583.01 ms 585.83 ms]
                        thrpt:  [915.37 µs/elem 910.95 µs/elem 893.31 µs/elem]
```
</details>

**Review by robik75 — APPROVED** [review]

**Pull request merged**
